### ISSUE TITLE
Suggestion: Ability To Hoist Bots

### ISSUE THREAD

**Issue by TheCuteFoxxy** [Sank6/Discord-Bot-List#401] opened 2020-12-17 06:06 UTC
Add a way for admins to hoist bots.

Such as being listed first on searches/being listed first on the home page.

Potentially with an icon in the corner of the bot card to indicate its status.

**Comment by ririko5834** [comment] 2020-12-17 11:44
Yes, good idea. Also I think that verified bots should have badge also on search and main page.

**Comment by ririko5834** [comment] 2020-12-18 07:25
I think that this is duplicate of https://github.com/Sank6/Discord-Bot-List/issues/357

**Comment by zennv** [comment] 2020-12-18 09:53
like being featured?

**Comment by ririko5834** [comment] 2020-12-18 11:09
Yes

**Comment by TheCuteFoxxy** [comment] 2020-12-18 18:11
It's not meant to be "certified" bots, its meant more as a reward system. Such as staff being able to give select bots a hoisted status temporarily.

**Comment by Sank6** [comment] 2020-12-19 00:51
Yeah this isn't really certified. I can understand how highlighting one or two bots manually is useful.

**Comment by shootdot** [comment] 2020-12-19 10:09
Ok for those who want to highlight any bot I can give u temporary code for it which I have made for my bot list.
Paste this code in `src/routes/index.js`
```js
const { Router } = require("express");
const Bots = require("@models/bots");
const bots = require("@routes/bots/index");
const tag = require("@routes/tag/index");
const api = require("@routes/api/index");
const theme = require("@routes/theme");

const route = Router();

route.use("/bots", bots);
route.use("/tag", tag);
route.use("/api", api);
route.use("/theme", theme);

route.get('/', async (req, res) => {

    let bot = await Bots.findOne({botid: 'botidhere'}, { _id: false, auth: false, __v: false, addedAt: false });
    if (!req.query.q) res.render('index', { req, bot: bot});
    else res.redirect(`/bots/search?q=${encodeURIComponent(req.query.q)}`)
});

module.exports = route;
```

And in `src/dynamic/index.pug`

```pug
doctype html
include includes/head.pug
body(onload="load()")
    include includes/nav.pug
    #content
        span.header
            h1 Discord Bot List
            p Just another bot list for Discord.
        #searchMore
            | Would you like to 
            a(href='/bots/search/') search all bots

        #cards
            if (bot)
                h2#subdiv Good Bot/Cool Bot/Hoisting Bot
                each val, i in bot
                    div.card
                        if (val.nsfw)
                            img.icon.nsfw(src=val.logo)
                        else
                            img.icon(src=val.logo)
                        h2.title #{val.username}
                            a.likes(href=`/bots/like/${val.botid}`)
                                i.far.fa-heart
                                | #{val.likes || 0}
                        p.desc #{val.description}
                        a.small.button(href=`/bots/${val.botid}`) View Bot
            h2#subdiv Random Bots
            span#loading Loading...
```

**Comment by ririko5834** [comment] 2020-12-19 11:27
Can you add option to hoist more bots at time? Also add command !hoist mention and !unhoist mention for that

**Comment by shootdot** [comment] 2020-12-19 13:14
Adding commands are too much difficult.

**Comment by shootdot** [comment] 2020-12-19 13:23
```js
const { Router } = require("express");
const Bots = require("@models/bots");
const bots = require("@routes/bots/index");
const tag = require("@routes/tag/index");
const api = require("@routes/api/index");
const theme = require("@routes/theme");

const route = Router();

route.use("/bots", bots);
route.use("/tag", tag);
route.use("/api", api);
route.use("/theme", theme);

route.get('/', async (req, res) => {
    let bot = [];
    /* Copy paste the below line if u want multiple bots to get hoisted
       Example :-
       bot = bot.concat(await Bots.findOne({botid: 'botidhere'}, { _id: false, auth: false, __v: false, addedAt: false }));
       bot = bot.concat(await Bots.findOne({botid: 'otherbotidhere'}, { _id: false, auth: false, __v: false, addedAt: false }));
     */

    bot = bot.concat(await Bots.findOne({botid: 'botidhere'}, { _id: false, auth: false, __v: false, addedAt: false }));

    if (!req.query.q) res.render('index', { req, bot: bot});
    else res.redirect(`/bots/search?q=${encodeURIComponent(req.query.q)}`)
});

module.exports = route;
```

**Comment by ririko5834** [comment] 2020-12-20 08:34
@shootdot But why you cant add commands and create mongodb array where will be saved hoisted bot ids.

**Comment by ririko5834** [comment] 2020-12-20 08:35
Also can you please send me code how to make custom (vanity) link for bot?

**Comment by Sank6** [comment] 2020-12-20 14:21
@ririko5834 That's the whole certified thing again. Having a snippet of code on the frontend to reorder the bots, or add a category is "temporary hoisting". Adding a property in MongoDB and setting a bot to be hoisted is a lot more complicated.

**Comment by shootdot** [comment] 2020-12-20 15:19
> @shootdot But why you cant add commands and create mongodb array where will be saved hoisted bot ids.

@ririko5834 
1) Changes in routes are not applied until you restart the whole botlist again.
2) But if you want to hoist bot's via discord bot command you need to create one more property in bot's mongoose model and make default to null. In `src/public/assets/js/cards.js` You need to add the code where you filter bots based on the property you created on bot's mongoose model then you need to edit the HTML code by getting the element id just like Sank6 did for random bots.
3) Doing this is not that easy and it's too complicated.

If Sank6 accepts I can create PR for this I have no issue on sharing code with others until Sank6 gives permission as this repository is maintained by Sank6

**Comment by Sank6** [comment] 2021-01-12 23:49
If you want to manually add a bot to the frontend hoisted, add this to `dynamic/index.pug`, under `#cards`
```pug
.card
  img.icon(src="IMAGE_ICON_URL")
  h2.title
    | BOT_NAME
  p.desc
    | BOT_DESCRIPTION
  a.button.small(href='LINK_TO_BOT') View info
```
It won't have bot likes because it's static content.

**Closed by Sank6** 2021-01-12 23:49 UTC
Labels: feature_request

**Comment by ririko5834** [comment] 2021-01-13 08:39
Please make command to hoist and unhoist bot.
